[versions]
com-android-application = "8.1.0-alpha11"
org-jetbrains-kotlin-android = "1.8.0"
core-ktx = "1.9.0"
appcompat = "1.6.1"
material = "1.8.0"
constraintlayout = "2.1.4"
com-android-library = "8.1.0-alpha11"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-application" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
com-android-library = { id = "com.android.library", version.ref = "com-android-library" }

[bundles]

